import type {
  AIConversation,
  BookingItem,
  CalendarEventItem,
  ChatRoom,
  CommunityItem,
  DocumentItem,
  FacilityItem,
  FeedItem,
  FriendCard,
  PlaceItem,
} from "@/lib/types";

export const postCatalog: FeedItem[] = [
  {
    id: "share-01",
    category: "sharing",
    title: "Anyone wants extra seminar notes?",
    description:
      "I cleaned up bilingual notes from last night's fire drill session and can share both PDF and printed copies.",
    tags: ["notes", "safety", "sharing"],
    authorId: "bobby-lee",
    authorName: "Bobby Lee",
    authorAvatar: "BL",
    createdAt: "2026-06-03T09:10:00+08:00",
    edited: false,
    likes: 18,
    comments: 6,
    owner: true,
  },
  {
    id: "share-02",
    category: "sharing",
    title: "Free yoga mat for pickup",
    description:
      "Still in good condition and recently cleaned. Happy to pass it on to a neighbor who actually uses it.",
    tags: ["free", "fitness"],
    authorId: "may-chan",
    authorName: "May Chan",
    authorAvatar: "MC",
    createdAt: "2026-06-03T07:00:00+08:00",
    edited: true,
    likes: 27,
    comments: 8,
    owner: false,
  },
  {
    id: "hand-01",
    category: "secondHand",
    title: "Compact air fryer",
    description:
      "Used for eight months only. Includes original basket and manual. Collection from Tower B lobby.",
    tags: ["kitchen", "appliance"],
    authorId: "chris-ho",
    authorName: "Chris Ho",
    authorAvatar: "CH",
    createdAt: "2026-06-02T20:10:00+08:00",
    edited: false,
    likes: 12,
    comments: 4,
    owner: false,
    price: 380,
  },
  {
    id: "hand-02",
    category: "secondHand",
    title: "Children's storybooks bundle",
    description:
      "Ten English and Chinese titles for ages 5 to 8. Free for any family in the estate.",
    tags: ["books", "kids"],
    authorId: "bobby-lee",
    authorName: "Bobby Lee",
    authorAvatar: "BL",
    createdAt: "2026-06-01T15:00:00+08:00",
    edited: false,
    likes: 9,
    comments: 3,
    owner: true,
    price: 0,
  },
  {
    id: "lf-01",
    category: "lostFound",
    title: "Lost silver key pouch near podium",
    description:
      "Small silver pouch with two keys and a blue access tag. Reward available if found before Thursday.",
    tags: ["keys", "reward"],
    authorId: "daisy-wong",
    authorName: "Daisy Wong",
    authorAvatar: "DW",
    createdAt: "2026-06-03T08:40:00+08:00",
    edited: false,
    likes: 0,
    comments: 2,
    owner: false,
    price: 120,
  },
  {
    id: "lf-02",
    category: "lostFound",
    title: "Found child water bottle at playroom",
    description:
      "Pink bottle with a rabbit sticker. I left it with the clubhouse desk and can confirm details in chat.",
    tags: ["found", "playroom"],
    authorId: "bobby-lee",
    authorName: "Bobby Lee",
    authorAvatar: "BL",
    createdAt: "2026-06-02T11:10:00+08:00",
    edited: false,
    likes: 0,
    comments: 1,
    owner: true,
    price: 0,
  },
  {
    id: "quest-01",
    category: "quest",
    title: "Pick up prescription before 20:00",
    description:
      "Need a trusted neighbor to collect a pharmacy order and drop it at Tower C concierge tonight.",
    tags: ["errand", "urgent"],
    authorId: "bobby-lee",
    authorName: "Bobby Lee",
    authorAvatar: "BL",
    createdAt: "2026-06-03T10:05:00+08:00",
    edited: false,
    likes: 0,
    comments: 2,
    owner: true,
    reward: 80,
    expiresAt: "2026-06-03T20:00:00+08:00",
    questState: "open",
    createdByCurrentUser: true,
  },
  {
    id: "quest-02",
    category: "quest",
    title: "Carry two boxes from lobby to Tower B",
    description:
      "Accepted yesterday. Needs completion before 19:00 tomorrow. Elevator booking already reserved.",
    tags: ["moving", "help"],
    authorId: "daisy-wong",
    authorName: "Daisy Wong",
    authorAvatar: "DW",
    createdAt: "2026-06-02T18:30:00+08:00",
    edited: false,
    likes: 0,
    comments: 0,
    owner: false,
    reward: 120,
    expiresAt: "2026-06-04T19:00:00+08:00",
    questState: "accepted",
    acceptedByCurrentUser: true,
  },
  {
    id: "quest-03",
    category: "quest",
    title: "Need someone to queue for contractor visit",
    description:
      "My renovation contractor arrives at 15:00 but I am stuck in transit. Need a neighbor to open the flat for inspection.",
    tags: ["contractor", "time-sensitive"],
    authorId: "ivan-yuen",
    authorName: "Ivan Yuen",
    authorAvatar: "IY",
    createdAt: "2026-06-03T12:00:00+08:00",
    edited: false,
    likes: 0,
    comments: 1,
    owner: false,
    reward: 200,
    expiresAt: "2026-06-03T15:00:00+08:00",
    questState: "dueSoon",
  },
];

export const deletedPostHistory: FeedItem[] = [
  {
    id: "history-1",
    category: "sharing",
    title: "Old donation notice",
    description: "Archived after the donation drive ended successfully.",
    tags: ["history"],
    authorId: "bobby-lee",
    authorName: "Bobby Lee",
    authorAvatar: "BL",
    createdAt: "2026-05-20T10:00:00+08:00",
    edited: false,
    likes: 8,
    comments: 1,
    owner: true,
  },
];

export const nearbyShops: PlaceItem[] = [
  {
    id: "shop-1",
    name: "Harbor Fresh Market",
    description: "Premium groceries, prepared meals, and weekly household essentials.",
    details: [
      "Today’s announcement: 10% off fruit boxes after 18:00.",
      "Queue updates are refreshed every hour.",
      "Community checkout support is available for senior residents.",
    ],
    phone: "+852 2568 1123",
    website: "https://example.com/harbor-fresh",
    lat: 22.2848,
    lng: 114.1589,
    updatedAt: "2026-06-03T11:20:00+08:00",
  },
  {
    id: "shop-2",
    name: "Lighthouse Cafe",
    description: "Casual coffee bar with private event booking and terrace seating.",
    details: [
      "This week: terrace acoustic set on Saturday evening.",
      "Private bookings support birthday parties and small resident meetups.",
      "Website booking form confirms within two business hours.",
    ],
    phone: "+852 2334 9100",
    website: "https://example.com/lighthouse-cafe",
    lat: 22.2856,
    lng: 114.1621,
    updatedAt: "2026-06-03T09:10:00+08:00",
  },
  {
    id: "shop-3",
    name: "Vital Pharmacy",
    description: "Prescription pickup, over-the-counter care, and home delivery coordination.",
    details: [
      "Prescription queue notices update live.",
      "Residents may book consultation windows for family pickup authorization.",
    ],
    phone: "+852 2888 0192",
    website: "N/A",
    lat: 22.2839,
    lng: 114.1602,
    updatedAt: "2026-06-03T08:45:00+08:00",
  },
];

export const nearbyCommunities: CommunityItem[] = [
  {
    id: "community-1",
    name: "Waterfront Residents Association",
    description: "Neighborhood volunteer group organizing cleanups and family activities.",
    details: [
      "Saturday: harbor cleanup and brunch meet-up.",
      "New residents can join as one-off volunteers or full members.",
      "Announcements include weather-related changes and meeting notes.",
    ],
    phone: "+852 6778 9001",
    website: "https://example.com/waterfront-ra",
    lat: 22.2863,
    lng: 114.1575,
    updatedAt: "2026-06-03T10:15:00+08:00",
    eventTitle: "Harbor cleanup and brunch",
    eventDate: "2026-06-08 09:00",
  },
  {
    id: "community-2",
    name: "Parents Social Circle",
    description: "Playdate coordination, parenting tips, and seasonal workshops for families.",
    details: [
      "This month: indoor storytelling session at the playroom.",
      "Volunteer host rotations are open for July.",
    ],
    phone: "+852 6112 2004",
    website: "https://example.com/parents-circle",
    lat: 22.2871,
    lng: 114.1614,
    updatedAt: "2026-06-03T07:55:00+08:00",
    eventTitle: "Storytelling afternoon",
    eventDate: "2026-06-10 15:30",
  },
];

export const chatRooms: ChatRoom[] = [
  {
    id: "chat-1",
    title: "Daisy Wong",
    members: ["Daisy Wong", "Bobby Lee"],
    preview: "Can you still help with the boxes tomorrow?",
    unreadCount: 2,
    online: true,
    group: false,
    messages: [
      {
        id: "msg-1",
        senderName: "Daisy Wong",
        senderAvatar: "DW",
        kind: "text",
        content: "Can you still help with the boxes tomorrow?",
        sentAt: "18:10",
        inbound: true,
      },
      {
        id: "msg-2",
        senderName: "System",
        senderAvatar: "TL",
        kind: "questRequest",
        content: "Quest accepted. Finish confirmation currently 1/2.",
        sentAt: "18:12",
        inbound: true,
        accentLabel: "Quest handover",
      },
      {
        id: "msg-3",
        senderName: "Bobby Lee",
        senderAvatar: "BL",
        kind: "text",
        content: "Yes. I’ll reach Tower B by 18:45 and message once I arrive.",
        sentAt: "18:14",
        inbound: false,
      },
    ],
  },
  {
    id: "chat-2",
    title: "Market pickup group",
    members: ["Bobby Lee", "May Chan", "Chris Ho"],
    preview: "Chris shared the booking link for Friday.",
    unreadCount: 0,
    online: true,
    group: true,
    messages: [
      {
        id: "msg-4",
        senderName: "Chris Ho",
        senderAvatar: "CH",
        kind: "text",
        content: "Chris shared the booking link for Friday.",
        sentAt: "11:02",
        inbound: true,
      },
      {
        id: "msg-5",
        senderName: "Bobby Lee",
        senderAvatar: "BL",
        kind: "text",
        content: "Great, I added the dinner reservation to calendar already.",
        sentAt: "11:18",
        inbound: false,
      },
    ],
  },
  {
    id: "chat-3",
    title: "Vital Pharmacy",
    members: ["Bobby Lee", "Vital Pharmacy"],
    preview: "Prescription order is ready for collection.",
    unreadCount: 1,
    online: false,
    group: false,
    messages: [
      {
        id: "msg-6",
        senderName: "Vital Pharmacy",
        senderAvatar: "VP",
        kind: "system",
        content: "Prescription order is ready for collection.",
        sentAt: "10:03",
        inbound: true,
        accentLabel: "Pickup notice",
      },
    ],
  },
];

export const friendSuggestions: FriendCard[] = [
  {
    id: "friend-s-1",
    name: "Phoebe Tang",
    username: "phoebe_t",
    avatar: "PT",
    bio: "Often helps organize family events and weekend swaps.",
    status: "online",
  },
  {
    id: "friend-s-2",
    name: "Boris Lam",
    username: "boris_lam",
    avatar: "BL",
    bio: "Runner, coffee enthusiast, and frequent community volunteer.",
    status: "offline",
  },
  {
    id: "friend-s-3",
    name: "Modboom Chow",
    username: "modboom",
    avatar: "MC",
    bio: "Helps with building documents and handyman referrals.",
    status: "busy",
  },
];

export const friendList: FriendCard[] = [
  {
    id: "friend-1",
    name: "May Chan",
    username: "mayc",
    avatar: "MC",
    bio: "Always collecting neighborhood tips for families and events.",
    status: "online",
  },
  {
    id: "friend-2",
    name: "Chris Ho",
    username: "chris.ho",
    avatar: "CH",
    bio: "Likes organizing group buys and facility bookings.",
    status: "offline",
  },
  {
    id: "friend-3",
    name: "Daisy Wong",
    username: "dwong",
    avatar: "DW",
    bio: "Building move-in expert and go-to helper for errands.",
    status: "busy",
  },
];

export const bookingStatuses: BookingItem[] = [
  {
    id: "booking-1",
    targetName: "Lighthouse Cafe terrace",
    organizer: "Bobby Lee",
    participantCount: 8,
    dateLabel: "Fri, 7 Jun · 19:00 to 21:00",
    status: "accepted",
  },
  {
    id: "booking-2",
    targetName: "107 Study Room",
    organizer: "Bobby Lee",
    participantCount: 3,
    dateLabel: "Sat, 8 Jun · 13:00 to 15:00",
    status: "pending",
  },
  {
    id: "booking-3",
    targetName: "Sky Lounge event space",
    organizer: "Bobby Lee",
    participantCount: 18,
    dateLabel: "Sun, 9 Jun · 14:00 to 18:00",
    status: "denied",
    reason: "Requested slot already reserved for a building meeting.",
  },
  {
    id: "booking-4",
    targetName: "Parents Circle workshop",
    organizer: "Bobby Lee",
    participantCount: 2,
    dateLabel: "Wed, 12 Jun · 15:30 to 17:00",
    status: "canceled",
  },
];

export const calendarEvents: CalendarEventItem[] = [
  {
    id: "event-1",
    title: "Lighthouse Cafe booking",
    description: "Terrace reservation confirmed for family gathering.",
    date: "2026-06-07",
    timeLabel: "19:00 - 21:00",
    type: "booking",
  },
  {
    id: "event-2",
    title: "Harbor cleanup and brunch",
    description: "Joined community volunteer event with residents association.",
    date: "2026-06-08",
    timeLabel: "09:00 - 11:30",
    type: "joined",
  },
  {
    id: "event-3",
    title: "Create welcome post draft",
    description: "Personal reminder to publish the new community intro post.",
    date: "2026-06-10",
    timeLabel: "20:00 - 20:30",
    type: "personal",
  },
  {
    id: "event-4",
    title: "Storytelling afternoon",
    description: "Join nearby community family session in the playroom.",
    date: "2026-06-10",
    timeLabel: "15:30 - 17:00",
    type: "joined",
  },
];

export const facilityItems: FacilityItem[] = [
  {
    id: "facility-1",
    roomName: "107 Study Room",
    category: "Quiet study",
    description: "Four-seat room with whiteboard, charging docks, and filtered lighting.",
    pricingRule: "$10 per hour",
    pricePreview: "$10 * 2 Hour(s) = $20",
    availability: [
      "10:00 - 12:00",
      "13:00 - 15:00",
      "16:00 - 18:00",
      "18:00 - 20:00 (Unavailable)",
    ],
  },
  {
    id: "facility-2",
    roomName: "Sky Lounge",
    category: "Event space",
    description: "Indoor lounge with skyline view, pantry access, and AV setup for celebrations.",
    pricingRule: "$260 flat booking + staffing fees for events over 20 guests",
    pricePreview: "$260 fixed booking fee",
    availability: ["09:00 - 12:00", "14:00 - 18:00", "19:00 - 22:00"],
  },
  {
    id: "facility-3",
    roomName: "Family Pool Deck",
    category: "Leisure",
    description: "Outdoor pool access billed per participant and session block.",
    pricingRule: "$35 per participant",
    pricePreview: "$35 * 3 Participants = $105",
    availability: ["08:00 - 10:00", "10:00 - 12:00", "15:00 - 17:00"],
  },
];

export const documentItems: DocumentItem[] = [
  {
    id: "doc-1",
    title: "Fire Safety and Emergency Routes",
    category: "Safety",
    updatedAt: "2026-05-26",
    summary: "Mandatory resident guidance for drills, exits, and alarm procedures.",
  },
  {
    id: "doc-2",
    title: "Renovation Hours and Noise Control",
    category: "Regulations",
    updatedAt: "2026-05-19",
    summary: "Approved work hours, permit requirements, and complaint channels.",
  },
  {
    id: "doc-3",
    title: "Clubhouse Booking Terms",
    category: "Facilities",
    updatedAt: "2026-05-29",
    summary: "Usage rules, cleanup responsibilities, and front desk payment instructions.",
  },
];

export const aiConversations: AIConversation[] = [
  {
    id: "ai-1",
    title: "Meeting room policy",
    createdAt: "2026-06-03T09:00:00+08:00",
    messages: [
      {
        id: "ai-msg-1",
        senderName: "Bobby Lee",
        senderAvatar: "BL",
        kind: "text",
        content: "What are the clubhouse rules for using the study rooms after 18:00?",
        sentAt: "09:02",
        inbound: false,
      },
      {
        id: "ai-msg-2",
        senderName: "To-Link AI",
        senderAvatar: "AI",
        kind: "system",
        content:
          "Study rooms remain bookable after 18:00, but food is prohibited and late arrivals beyond 15 minutes may release the slot.",
        sentAt: "09:02",
        inbound: true,
      },
    ],
  },
  {
    id: "ai-2",
    title: "Building manager contact",
    createdAt: "2026-06-02T15:00:00+08:00",
    messages: [
      {
        id: "ai-msg-3",
        senderName: "Bobby Lee",
        senderAvatar: "BL",
        kind: "text",
        content: "Who handles weekend maintenance escalations?",
        sentAt: "15:10",
        inbound: false,
      },
      {
        id: "ai-msg-4",
        senderName: "To-Link AI",
        senderAvatar: "AI",
        kind: "system",
        content:
          "Weekend maintenance escalation is routed to the duty manager first, then the on-call contractor if building systems are affected.",
        sentAt: "15:10",
        inbound: true,
      },
    ],
  },
];